version: '3.4'

services:

      devenv:
        tty: true
        stdin_open: true
        build: .
        container_name: devenv
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        command: 
          - /bin/sh
          - -c
          - |
            python3 inf.py
        ports:
          - 1234:1234
        volumes:
          - ./:/devenv

      